apiVersion: v1
kind: Pod
metadata:
  name: http-request-logger
  labels:
    app: http-request-logger
spec:
  containers:
  - name: http-request-logger
    image: http-request-logger:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: http-request-logger-service
spec:
  selector:
    app: http-request-logger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080